### PR TITLE
DM-6574: Switch to bibtex

### PR DESCRIPTION
**Pull request by timj**
This continues @melissagraham's work on bibtex-ing LDM-151. Unfortunately the document has moved on a lot since @melissagraham put together the initial bib file. I've added some more items but there are still some unknowns that I need some help with:
```
Warning--I didn't find a database entry for "dokkum01"
Warning--I didn't find a database entry for "citation_needed"
Warning--I didn't find a database entry for "Sick2013"
Warning--I didn't find a database entry for "tabor04"
Warning--I didn't find a database entry for "???"
```

### CODE REVIEW

**Comment by timj** [comment]
For the missing references:

* @SimonKrughoff I think you added "Sick2013", "tabor04", "citation_needed",  and "dokkum01".
* @connolly do you know what "???" should be yet?

**Comment by SimonKrughoff** [comment]
dokkum01 should be:
@ARTICLE{2001PASP..113.1420V,
   author = {{van Dokkum}, P.~G.},
    title = "{Cosmic-Ray Rejection by Laplacian Edge Detection}",
  journal = {\pasp},
   eprint = {astro-ph/0108003},
 keywords = {Instrumentation: Detectors, Methods: Data Analysis-techniques: image processing},
     year = 2001,
    month = nov,
   volume = 113,
    pages = {1420-1427},
      doi = {10.1086/323894},
   adsurl = {http://adsabs.harvard.edu/abs/2001PASP..113.1420V},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

I didn't add this, but I believe Sick2013 should be the following:
@ARTICLE{2014AJ....147..109S,
   author = {{Sick}, J. and {Courteau}, S. and {Cuillandre}, J.-C. and {McDonald}, M. and 
	{de Jong}, R. and {Tully}, R.~B.},
    title = "{Andromeda (M31) Optical and Infrared Disk Survey. I. Insights in Wide-field Near-IR Surface Photometry}",
  journal = {\aj},
archivePrefix = "arXiv",
   eprint = {1303.6290},
 primaryClass = "astro-ph.IM",
 keywords = {methods: observational, techniques: photometric },
     year = 2014,
    month = may,
   volume = 147,
      eid = {109},
    pages = {109},
      doi = {10.1088/0004-6256/147/5/109},
   adsurl = {http://adsabs.harvard.edu/abs/2014AJ....147..109S},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

tabor04 should be:
@ARTICLE{2007PASA...24..189T,
   author = {{Tabur}, V.},
    title = "{Fast Algorithms for Matching CCD Images to a Stellar Catalogue}",
  journal = {\pasa},
archivePrefix = "arXiv",
   eprint = {0710.3618},
 keywords = {astrometry, methods: data analysis, surveys},
     year = 2007,
    month = dec,
   volume = 24,
    pages = {189-198},
      doi = {10.1071/AS07028},
   adsurl = {http://adsabs.harvard.edu/abs/2007PASA...24..189T},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

**Comment by SimonKrughoff** [comment]
citation_needed is actually a reference to a patent, I don't know how that should be referenced.  Google Patents offers the following bibtex entry:
@misc{c1962method,
  title={Method and means for recognizing complex patterns},
  author={C, H.P.V.},
  url={https://www.google.com/patents/US3069654},
  year={1962},
  month=dec # "~18",
  publisher={Google Patents},
  note={US Patent 3,069,654}
}

**Comment by SimonKrughoff** [comment]
@connolly I assume this is the reference you meant:

@ARTICLE{2010ApJ...719...59K,
   author = {{Kerekes}, G. and {Budav{\'a}ri}, T. and {Csabai}, I. and {Connolly}, A.~J. and 
	{Szalay}, A.~S.},
    title = "{Cross Identification of Stars with Unknown Proper Motions}",
  journal = {\apj},
archivePrefix = "arXiv",
   eprint = {1006.2096},
 keywords = {astrometry, catalogs, methods: statistical, stars: statistics},
     year = 2010,
    month = aug,
   volume = 719,
    pages = {59-66},
      doi = {10.1088/0004-637X/719/1/59},
   adsurl = {http://adsabs.harvard.edu/abs/2010ApJ...719...59K},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

**Pull request merged**
